// <auto-generated />
using IndividuellOppgave_s315278.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IndividuellOppgave_s315278.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20181117213238_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IndividuellOppgave_s315278.Model.FAQModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("answer");

                    b.Property<string>("asker");

                    b.Property<string>("category");

                    b.Property<string>("question");

                    b.Property<int>("totalVotes");

                    b.Property<int>("upVotes");

                    b.HasKey("id");

                    b.ToTable("FAQ");

                    b.HasData(
                        new { id = 1, answer = "Før du logger inn kan du se hvilke filmer som er til salgs. Ved å trykke Logg inn og fylle inn epost og passord, kan du nå velge å kjøpe filmer, eller du kan administrere dine tidligere kjøp.", asker = "per@hansen.no", category = "Navigasjon", question = "Hvordan fungerer filmkjøp?", totalVotes = 15, upVotes = 12 },
                        new { id = 2, answer = "Trykk på Logg inn-knappen i øvre høyre hjørne, velg Registrer, og fyll ut informasjonen din.", asker = "per@nilsen.no", category = "Navigasjon", question = "Hvordan registrerer jeg meg?", totalVotes = 3, upVotes = 3 },
                        new { id = 3, answer = "Per dags dato er det 24 filmer å velge mellom, men utvalget vokser regelmessig. Følg med!", asker = "nils@hansen.no", category = "Innhold", question = "Hvor mange filmer finnes det å velge mellom?", totalVotes = 12, upVotes = 10 },
                        new { id = 4, answer = "Utvalget vårt avhenger av vår leverandørs rettigheter, men ta kontakt med oss på mail, så kan vi sjekke det opp!", asker = "hans@nilsen.no", category = "Innhold", question = "Kan dere skaffe en spesifikk film?", totalVotes = 20, upVotes = 3 },
                        new { id = 5, answer = "På alle våre filmer han man velge engelske eller skandinaviske undertekster.", asker = "nils@hansen.no", category = "Innhold", question = "Hvilke alternativer finnes for undertekster?", totalVotes = 15, upVotes = 15 },
                        new { id = 6, answer = "Vi aksepterer Visa, MasterCard, og BankAxept.", asker = "peter@davidson.com", category = "Faktura", question = "Hvilke kredittkort kan jeg bruke?", totalVotes = 5, upVotes = 2 },
                        new { id = 7, answer = "Det er helt trygt å handle av Lunaflick. Vi krypterer all informasjon, og betalingsinformasjonen lagres ikke av oss.", asker = "pierre@chanson.no", category = "Faktura", question = "Er det trygt å handle i denne nettbutikken?", totalVotes = 5, upVotes = 5 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
